# Generated by Django 3.2.7 on 2021-10-15 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptoms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
